// import About from "./components/About";
// import Contact from "./components/Contact";
// import Create from "./components/Create";
// import GetStarted from "./components/GetStarted";
// import MarketPlace from "./components/MarketPlace";
// import Service from "./components/Service";
// import SingleOrder from "./components/SingleOrder";
// import Team from "./components/Team";
// import Layout from "./components/Layout";

export { default as Home } from "./pages/Home";
export { default as About } from "./components/About";
export { default as Contact } from "./components/Contact";
export { default as Create } from "./components/Create";
export { default as GetStarted } from "./components/GetStarted";
export { default as MarketPlace } from "./components/MarketPlace";
export { default as Service } from "./components/Service";
export { default as SingleOrder } from "./components/SingleOrder";
export { default as Team } from "./components/Team";
export { default as Layout } from "./components/Layout";
